"""
admelab.naming_smart
====================
**Self-verified** IUPAC naming for analog libraries.

Core idea - every emitted name is checked by a *round-trip*:

    candidate name ──OPSIN──▶ structure ──▶ InChIKey
                                              │ == InChIKey of the real molecule?
    real molecule ──────────────▶ InChIKey ───┘
        match     -> PROVABLY correct name (verified=True)
        no match  -> discarded

Sources of candidate names (cascade), all filtered by the validator:
  1. **Provenance**: if the analog was generated by decoration, we know which
     substituent was added; we build the name from the lead's and enumerate
     locants, letting the round-trip pick the correct one. Fast, offline and
     covers cases where web resolvers fail.
  2. **PubChem** (exact for known molecules).
  3. **CACTUS** (NCI algorithmic resolver for novel molecules).

Requires a JRE + OPSIN in `~/adme/tools/` (see tools_setup.sh). Without them,
the module degrades to PubChem/CACTUS without verification.
"""
from __future__ import annotations

import glob
import itertools
import os
import re as _re
import subprocess
from typing import Optional, Sequence

from rdkit import Chem

from . import naming as _naming  # reuse PubChem/CACTUS


# ---------------------------------------------------------------------------
# Locating JRE + OPSIN
# ---------------------------------------------------------------------------
def _locate_tools() -> tuple[Optional[str], Optional[str]]:
    """Find the portable java binary and opsin.jar. Allows override via the
    environment variables ADMELAB_JAVA and ADMELAB_OPSIN."""
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)                 # ~/adme
    tools = os.path.join(root, "tools")

    java = os.environ.get("ADMELAB_JAVA")
    if not java or not os.path.exists(java):
        hits = glob.glob(os.path.join(tools, "jdk-*", "bin", "java"))
        java = hits[0] if hits else None

    opsin = os.environ.get("ADMELAB_OPSIN")
    if not opsin or not os.path.exists(opsin):
        cand = os.path.join(tools, "opsin.jar")
        opsin = cand if os.path.exists(cand) else None

    return java, opsin


JAVA_BIN, OPSIN_JAR = _locate_tools()


def opsin_available() -> bool:
    return bool(JAVA_BIN and OPSIN_JAR)


# ---------------------------------------------------------------------------
# OPSIN bridge (name -> SMILES), batched (single JVM startup)
# ---------------------------------------------------------------------------
def opsin_to_smiles(names: Sequence[str]) -> list[Optional[str]]:
    """Convert a list of IUPAC names to SMILES with OPSIN. Returns an aligned
    list (None where OPSIN could not interpret the name)."""
    names = list(names)
    if not names or not opsin_available():
        return [None] * len(names)
    proc = subprocess.run(
        [JAVA_BIN, "-jar", OPSIN_JAR, "-o", "smi"],
        input="\n".join(names), capture_output=True, text=True,
    )
    out = proc.stdout.splitlines()
    out += [""] * (len(names) - len(out))        # pad if OPSIN shortened
    return [(s.strip() or None) for s in out[:len(names)]]


def _inchikey(smiles: Optional[str]) -> Optional[str]:
    if not smiles:
        return None
    m = Chem.MolFromSmiles(smiles)
    return Chem.MolToInchiKey(m) if m else None


# ---------------------------------------------------------------------------
# Provenance-based naming
# ---------------------------------------------------------------------------
# IUPAC prefixes/suffixes of the substituents used in generation.py.
SUBST_IUPAC_PREFIX: dict[str, str] = {
    "fluoro":          "fluoro",
    "chloro":          "chloro",
    "bromo":           "bromo",
    "methyl":          "methyl",
    "ethyl":           "ethyl",
    "isopropyl":       "propan-2-yl",
    "cyclopropyl":     "cyclopropyl",
    "trifluoromethyl": "trifluoromethyl",
    "hydroxy":         "hydroxy",
    "methoxy":         "methoxy",
    "trifluoromethoxy": "trifluoromethoxy",
    "amino":           "amino",
    "dimethylamino":   "dimethylamino",
    "cyano":           "cyano",
    "nitro":           "nitro",
    "carboxy":         "carboxy",
    "acetyl":          "acetyl",
    "carboxamide":     "carbamoyl",
    "sulfonamide":     "sulfamoyl",
    "phenyl":          "phenyl",
}

# "Ring base" tokens where we insert aromatic substituents.
# The attachment point / principal group fixes C1, so new substituents take
# locants 2..6 (we try them all and the round-trip filters out clashes).
_RING_TOKENS = [
    "phenyl", "benzoic acid", "benzamide", "benzenesulfonamide",
    "benzonitrile", "aniline", "phenol", "anisole", "benzene",
]
_RING_LOCANTS = [2, 3, 4, 5, 6]


def _insert_prefixes(lead_name: str, token: str, assignment: Sequence[tuple[int, str]]) -> Optional[str]:
    """Insert 'loc-prefix[-loc-prefix...]' right before `token` in the lead
    name, with the appropriate separating hyphen."""
    idx = lead_name.find(token)
    if idx < 0:
        return None
    before = lead_name[:idx]
    prefstr = "-".join(f"{loc}-{pref}" for loc, pref in assignment)
    sep = "-" if (before and before[-1] not in "[(- ") else ""
    return f"{before}{sep}{prefstr}{lead_name[idx:]}"


def _prefix_variants(pref: str) -> list[str]:
    """Prefix forms to try, preferring the canonical one (parenthesized for
    compound substituents). The round-trip picks the one that validates; by
    iterating in this order we prefer the more correct form when both work."""
    needs_paren = ("-" in pref) or ("trifluoro" in pref) or ("difluoro" in pref)
    if needs_paren and not pref.startswith("("):
        return [f"({pref})", pref]
    return [pref]


def provenance_candidates(lead_name: str, prefixes: Sequence[str]) -> list[str]:
    """Generate candidate names by inserting `prefixes` (1 or 2 new substituents)
    into each ring token of the lead name, enumerating locants and prefix forms.
    The round-trip validator picks the correct one."""
    if not lead_name or not prefixes:
        return []
    k = len(prefixes)
    variant_lists = [_prefix_variants(p) for p in prefixes]
    cands: list[str] = []
    for token in _RING_TOKENS:
        if token not in lead_name:
            continue
        if k == 1:
            for pv in variant_lists[0]:
                for loc in _RING_LOCANTS:
                    c = _insert_prefixes(lead_name, token, [(loc, pv)])
                    if c:
                        cands.append(c)
        elif k == 2:
            for pv0 in variant_lists[0]:
                for pv1 in variant_lists[1]:
                    for locs in itertools.permutations(_RING_LOCANTS, 2):
                        assignment = [(locs[0], pv0), (locs[1], pv1)]
                        c = _insert_prefixes(lead_name, token, assignment)
                        if c:
                            cands.append(c)
        # k>=3: not enumerated by provenance (falls back to the web cascade)
        break  # use only the first ring token found
    # unique, preserving order (canonical forms first)
    seen, uniq = set(), []
    for c in cands:
        if c not in seen:
            seen.add(c); uniq.append(c)
    return uniq


def _prefixes_from_provenance(prov: dict) -> Optional[list[str]]:
    """Translate generation provenance into IUPAC prefixes. None if not applicable."""
    if not prov or prov.get("method") != "decoration":
        return None
    subs = prov.get("substituents") or []
    prefixes = [SUBST_IUPAC_PREFIX.get(s) for s in subs]
    if not prefixes or any(p is None for p in prefixes) or len(prefixes) > 2:
        return None
    return prefixes


# ---------------------------------------------------------------------------
# High-level cascade, with verification
# ---------------------------------------------------------------------------
def smart_name_batch(
    smiles_list: Sequence[str],
    provenance: Optional[Sequence[Optional[dict]]] = None,
    lead_smiles: Optional[str] = None,
    lead_name: Optional[str] = None,
    use_web: bool = True,
    progress: bool = True,
) -> "pd.DataFrame":
    """Name a list of SMILES with round-trip verification.

    Returns a DataFrame [SMILES, iupac_name, name_source, iupac_verified].
      - name_source: 'provenance' | 'pubchem' | 'cactus' | None
      - iupac_verified: True if OPSIN reconstructs the exact structure.

    provenance : list aligned with smiles_list, with each analog's provenance
                 dict (from GenerationResult.provenance); None if absent.
    lead_name  : IUPAC name of the lead; if None it is resolved once.
    """
    import pandas as pd

    smiles_list = list(smiles_list)
    n = len(smiles_list)
    if provenance is None:
        provenance = [None] * n

    # Lead name (once) for the provenance path.
    if lead_name is None and lead_smiles and opsin_available():
        got = _naming.iupac_name(lead_smiles)   # PubChem -> CACTUS
        lead_name = got.get("iupac_name")

    # 1) Gather ALL provenance candidates and their target molecule.
    targets = [_inchikey(s) for s in smiles_list]
    all_cands: list[str] = []
    cand_owner: list[int] = []                  # molecule index per candidate
    if lead_name and opsin_available():
        for i, prov in enumerate(provenance):
            prefixes = _prefixes_from_provenance(prov)
            if not prefixes:
                continue
            for c in provenance_candidates(lead_name, prefixes):
                all_cands.append(c); cand_owner.append(i)

    # 2) Validate all provenance candidates in a single OPSIN batch.
    results = [{"SMILES": s, "iupac_name": None, "name_source": None,
                "iupac_verified": False} for s in smiles_list]
    if all_cands:
        cand_smiles = opsin_to_smiles(all_cands)
        cand_keys = [_inchikey(cs) for cs in cand_smiles]
        for name, owner, key in zip(all_cands, cand_owner, cand_keys):
            if results[owner]["iupac_verified"]:
                continue
            if key is not None and key == targets[owner]:
                results[owner].update(iupac_name=name, name_source="provenance",
                                      iupac_verified=True)

    # 3) For the rest, web cascade (PubChem -> CACTUS) + verification.
    if use_web:
        iterator = range(n)
        if progress:
            try:
                from tqdm.auto import tqdm
                iterator = tqdm(iterator, desc="Naming (verified IUPAC)")
            except ImportError:
                pass
        for i in iterator:
            if results[i]["iupac_name"]:
                continue
            got = _naming.iupac_name(smiles_list[i])   # PubChem -> CACTUS
            nm, src = got.get("iupac_name"), got.get("name_source")
            if not nm:
                continue
            # round-trip verification if OPSIN is available
            verified = False
            if opsin_available():
                key = _inchikey(opsin_to_smiles([nm])[0])
                verified = (key is not None and key == targets[i])
            results[i].update(iupac_name=nm, name_source=src, iupac_verified=verified)

    return pd.DataFrame(results)


def smart_name(
    smiles: str,
    provenance: Optional[dict] = None,
    lead_smiles: Optional[str] = None,
    lead_name: Optional[str] = None,
) -> dict:
    """Single-molecule version. Returns a dict with name/source/verified."""
    df = smart_name_batch([smiles], provenance=[provenance],
                          lead_smiles=lead_smiles, lead_name=lead_name,
                          progress=False)
    row = df.iloc[0].to_dict()
    return row


# ---------------------------------------------------------------------------
# ESTER naming by provenance
#   An ester is named "<alcohol radical> <acid turned into -ate>",
#   e.g. "benzyl 1-oxido-2,1,3-benzoxadiazol-1-ium-5-carboxylate".
#   Knowing the acid name and the alcohol name, we compose the ester name and
#   validate it by round-trip like the rest of the module.
# ---------------------------------------------------------------------------
def acyl_variants(acid_name: str) -> list[str]:
    """Turn an acid name into its salt/ester (-ate) form."""
    n = (acid_name or "").strip()
    out: list[str] = []
    if n.endswith("carboxylic acid"):
        out.append(n[: -len("carboxylic acid")] + "carboxylate")
    if n.endswith("oic acid"):
        out.append(n[: -len("oic acid")] + "oate")
    if n.endswith("ic acid"):
        out.append(n[: -len("ic acid")] + "ate")
    return list(dict.fromkeys(out)) or ([n] if n else [])


def radical_variants(alcohol_name: str) -> list[str]:
    """Derive possible radical (R-) names from an alcohol name.

    Generates several forms (e.g. 'cyclohexanol' -> 'cyclohexanyl', 'cyclohexyl');
    the round-trip validator keeps the one that reconstructs the structure.
    """
    n = (alcohol_name or "").strip()
    if not n:
        return []
    out: list[str] = []
    if n.lower().endswith(" alcohol"):
        out.append(n[: -len(" alcohol")])
    if n.lower().endswith("methanol"):
        out.append(n[: -len("methanol")] + "methyl")
    if n.lower().endswith("anol"):
        out.append(n[:-4] + "yl")
    if n.lower().endswith("ol"):
        out.append(n[:-2] + "yl")
    # variants without leading stereodescriptors, e.g. "(1R,2S,5R)-..."
    for v in list(out):
        stripped = _re.sub(r"^\([0-9RSEZrsez,\-\s]+\)-", "", v)
        if stripped != v:
            out.append(stripped)
    return list(dict.fromkeys(out))


def ester_name_candidates(acid_name: str, alcohol_name: str) -> list[str]:
    """Candidate IUPAC names for the ester of `acid_name` with `alcohol_name`."""
    acyls = acyl_variants(acid_name)
    radicals = radical_variants(alcohol_name)
    return [f"{r} {a}" for a in acyls for r in radicals]


def name_esters_batch(
    ester_smiles: Sequence[str],
    alcohol_smiles: Sequence[str],
    acid_smiles: Optional[str] = None,
    acid_name: Optional[str] = None,
    alcohol_names: Optional[Sequence[Optional[str]]] = None,
    use_web: bool = True,
    progress: bool = True,
) -> "pd.DataFrame":
    """Name ESTERS by composing 'radical + acyl' and verifying by round-trip.

    Strategy: resolve the acid name once and, for each ester, the starting
    alcohol name (PubChem/CACTUS, which usually know the alcohols even if not
    the ester). Compose candidates, validate them all in a single OPSIN batch
    and, if none matches, fall back to naming the ester directly via the web.

    Returns [SMILES, iupac_name, name_source, iupac_verified].
    """
    import pandas as pd

    ester_smiles = list(ester_smiles)
    alcohol_smiles = list(alcohol_smiles)
    n = len(ester_smiles)

    if acid_name is None and acid_smiles:
        acid_name = _naming.iupac_name(acid_smiles).get("iupac_name")

    # Alcohol names (cached by SMILES to avoid repeated queries).
    if alcohol_names is None:
        cache: dict[str, Optional[str]] = {}
        alcohol_names = []
        it = alcohol_smiles
        if progress:
            try:
                from tqdm.auto import tqdm
                it = tqdm(alcohol_smiles, desc="Resolving alcohols")
            except ImportError:
                pass
        for s in it:
            if s not in cache:
                cache[s] = _naming.iupac_name(s).get("iupac_name") if use_web else None
            alcohol_names.append(cache[s])

    targets = [_inchikey(s) for s in ester_smiles]
    results = [{"SMILES": s, "iupac_name": None, "name_source": None,
                "iupac_verified": False} for s in ester_smiles]

    # Composed candidates, validated in a single batch.
    all_cands: list[str] = []
    owner: list[int] = []
    if acid_name and opsin_available():
        for i, an in enumerate(alcohol_names):
            for c in ester_name_candidates(acid_name, an or ""):
                all_cands.append(c); owner.append(i)
    if all_cands:
        keys = [_inchikey(s) for s in opsin_to_smiles(all_cands)]
        for name, i, k in zip(all_cands, owner, keys):
            if results[i]["iupac_verified"]:
                continue
            if k is not None and k == targets[i]:
                results[i].update(iupac_name=name, name_source="provenance-ester",
                                  iupac_verified=True)

    # Fallback: name the ester directly via the web (verify if possible).
    if use_web:
        for i in range(n):
            if results[i]["iupac_name"]:
                continue
            got = _naming.iupac_name(ester_smiles[i])
            nm, src = got.get("iupac_name"), got.get("name_source")
            if not nm:
                continue
            verified = False
            if opsin_available():
                k = _inchikey(opsin_to_smiles([nm])[0])
                verified = (k is not None and k == targets[i])
            results[i].update(iupac_name=nm, name_source=src, iupac_verified=verified)

    return pd.DataFrame(results)


def name_dataframe(
    df: "pd.DataFrame",
    gen_result=None,
    lead_smiles: Optional[str] = None,
    lead_name: Optional[str] = None,
    smiles_col: str = "SMILES",
    use_web: bool = True,
    progress: bool = True,
) -> "pd.DataFrame":
    """Name the rows of a DataFrame (e.g. the *top*) reusing the provenance of a
    GenerationResult for the verified offline path.

    Returns a copy of `df` with columns [iupac_name, name_source,
    iupac_verified] added (joined on SMILES).
    """
    prov_map: dict[str, dict] = {}
    if gen_result is not None:
        for prov in getattr(gen_result, "provenance", []):
            if prov.get("smiles"):
                prov_map[prov["smiles"]] = prov

    smis = df[smiles_col].tolist()
    prov = [prov_map.get(s) for s in smis]
    named = smart_name_batch(smis, provenance=prov, lead_smiles=lead_smiles,
                             lead_name=lead_name, use_web=use_web, progress=progress)
    return df.merge(named, on=smiles_col, how="left")
